Repository aziontech/azion, pull requests merged in 2024-07, with the labels that each got.

#879 feat: output link
  pkg/cmd/link/link.go
Labels: enhancement

#881 feat: output build
  pkg/cmd/build/utils.go
Labels: enhancement

#886 fix: deploy command calls build and executes the build print
  pkg/cmd/build/build.go
  pkg/cmd/build/run.go
  pkg/cmd/build/utils.go
  pkg/cmd/build/vulcan.go
  pkg/cmd/deploy/bucket.go
  pkg/cmd/deploy/deploy.go
  pkg/cmd/deploy/purge.go
  pkg/cmd/deploy/requests.go
  pkg/cmd/dev/dev.go
Labels: wontfix

#895 fix: correct format fields
  pkg/cmd/list/cache_setting/cache_setting.go
  pkg/cmd/list/domain/domain.go
  pkg/cmd/list/edge_applications/edge_applications.go
  pkg/cmd/list/edge_function/edge_function.go
  pkg/cmd/list/edge_storage/object.go
  pkg/cmd/list/origin/origin.go
  pkg/cmd/list/personal_token/personal_token.go
  pkg/cmd/list/rule_engine/rule_engine.go
  pkg/cmd/list/variables/variables.go
Labels: bug

#897 test: cmd create
  .gitignore
  pkg/cmd/create/domain/domain.go
  pkg/cmd/create/domain/domain_test.go
  pkg/cmd/create/edge_applications/edge_application.go
  pkg/cmd/create/edge_applications/edge_application_test.go
  pkg/cmd/create/edge_applications/fixtures/request_full.json
  pkg/cmd/create/edge_function/edge_function_test.go
  pkg/cmd/create/edge_storage/edge_storage.go
  pkg/cmd/create/edge_storage/models.go
  pkg/cmd/create/edge_storage/object.go
  pkg/cmd/create/edge_storage/object_test.go
  pkg/cmd/create/origin/origin.go
  pkg/cmd/create/origin/origin_test.go
  pkg/cmd/create/personal_token/personal_token.go
  pkg/cmd/create/rules_engine/rules_engine.go
  pkg/cmd/create/rules_engine/rules_engine_test.go
  utils/helpers.go
Labels: Testing

#901 test: utils
  pkg/cmd/create/edge_function/edge_function.go
  pkg/cmd/create/edge_storage/bucket.go
  pkg/cmd/create/origin/origin.go
  pkg/cmd/update/edge_storage/bucket.go
  utils/helpers.go
  utils/helpers_test.go
Labels: Testing

#905 fix: check if .edge/storage exists before purging files
  pkg/cmd/deploy/purge.go
  pkg/cmd/dev/dev.go
Labels: bug

#907 feat: detect package manager auto
  messages/init/messages.go
  messages/link/messages.go
  pkg/cmd/init/init.go
  pkg/cmd/init/utils.go
  pkg/cmd/link/link.go
  pkg/cmd/link/utils.go
  pkg/node/node.go
  utils/helpers.go
  utils/helpers_test.go
Labels: enhancement
