Repository aziontech/azion, pull requests merged in 2024-08, with the labels that each got.

#923 test: add unit tests for the log commands
  pkg/cmd/logs/cells/cells.go
  pkg/cmd/logs/cells/cells_test.go
  pkg/cmd/logs/http/http.go
  pkg/cmd/logs/http/http_test.go
Labels: Testing

#924 chore: better output error
  pkg/output/error.go
Labels: chore

#929 feat: add domain and purge management through azion.config to CLI
  messages/manifest/errors.go
  messages/manifest/messages.go
  pkg/cmd/deploy/deploy.go
  pkg/contracts/contracts.go
  pkg/manifest/manifest.go
  pkg/manifest/request.go
  pkg/vulcan/vulcan.go
  pkg/vulcan/vulcan_test.go
Labels: feature

#933 fix: invalid cross-device link
  pkg/cmd/init/init.go
  pkg/vulcan/vulcan.go
  pkg/vulcan/vulcan_test.go
Labels: bug
