Repository aziontech/azion, pull requests merged in 2024-02, with the labels that each got.

#662 feat: add logs command
  Makefile
  go.mod
  go.sum
  messages/logs/cells/errors.go
  messages/logs/cells/messages.go
  pkg/api/graphql/cells/cells.go
  pkg/api/graphql/messages.go
  pkg/cmd/logs/cells/cells.go
  pkg/cmd/logs/logs.go
  pkg/cmd/root/root.go
Labels: enhancement

#664 feat: add http events logs
  messages/logs/http/errors.go
  messages/logs/http/messages.go
  pkg/api/graphql/cells/cells.go
  pkg/api/graphql/http/http.go
  pkg/cmd/logs/http/http.go
  pkg/cmd/logs/logs.go
Labels: enhancement

#671 fix: add missing fields in origin create/update
  messages/origin/messages.go
  pkg/cmd/create/origin/origin.go
  pkg/cmd/create/origin/origin_test.go
  pkg/cmd/update/origin/origin.go
  utils/helpers.go
Labels: bug

#674 fix: static deprecated
  pkg/cmd/deploy/manifest.go
  pkg/cmd/link/link.go
  pkg/cmd/link/link_test.go
  pkg/cmd/link/simple.go
  pkg/cmd/link/static.go
  pkg/cmd/link/utils.go
Labels: bug

#678 fix: item empty removed in presets
  pkg/cmd/link/utils.go
Labels: bug

#677 Deploy to Production - 2024/02/09
  pkg/cmd/deploy/manifest.go
  pkg/cmd/link/link.go
  pkg/cmd/link/link_test.go
  pkg/cmd/link/simple.go
  pkg/cmd/link/static.go
  pkg/cmd/link/utils.go
Labels: bug

#675 feat: add metrics collector to all commands
  messages/root/messages.go
  pkg/cmd/init/init.go
  pkg/cmd/init/utils.go
  pkg/cmd/link/link.go
  pkg/cmd/link/utils.go
  pkg/cmd/root/post_command.go
  pkg/cmd/root/pre_command.go
  pkg/cmd/root/root.go
  pkg/token/models.go
  utils/helpers.go
Labels: enhancement

#679 feat: send metrics to Segment
  .github/workflows/deploy_prod.yml
  .github/workflows/deploy_stage.yml
  .goreleaser.yaml
  Makefile
  env/prod
  go.mod
  go.sum
  pkg/cmd/login/login.go
  pkg/cmd/root/pre_command.go
  pkg/metric/.fixtures/metrics.json
  pkg/metric/metric.go
  pkg/token/models.go
  pkg/token/token.go
  pkg/token/token_test.go
Labels: enhancement

#682 refactor: routes next
  pkg/cmd/deploy/manifest.go
Labels: refactor

#684 fix: enable flag global
  pkg/cmd/init/utils.go
  pkg/cmd/link/utils.go
  pkg/cmd/root/post_command.go
  pkg/cmd/root/pre_command.go
  pkg/cmd/unlink/utils.go
  utils/helpers.go
Labels: bug

#685 fix: check command completion ignored metrics
  Makefile
  env/prod
  pkg/cmd/root/pre_command.go
  pkg/metric/metric.go
Labels: bug

#686 Deploy to Production - 2024/02/16
  Makefile
  env/prod
  pkg/cmd/deploy/manifest.go
  pkg/cmd/init/utils.go
  pkg/cmd/link/utils.go
  pkg/cmd/root/post_command.go
  pkg/cmd/root/pre_command.go
  pkg/cmd/unlink/utils.go
  pkg/metric/metric.go
  utils/helpers.go
Labels: bug

#690 fix: create cache policy and define cache for function
  pkg/api/edge_applications/cache_setting.go
  pkg/cmd/deploy/manifest.go
Labels: bug

#689 feat: properties metrics
  go.mod
  go.sum
  pkg/cmd/root/pre_command.go
  pkg/cmd/root/root.go
  pkg/github/github.go
  pkg/metric/count.go
  pkg/metric/segment.go
Labels: enhancement

#688 fix: deploy was not writing domain id to azion.json #patch
  messages/deploy/messages.go
  pkg/cmd/deploy/bucket.go
  pkg/cmd/deploy/requests.go
Labels: bug

#696 feat: add whoami command
  messages/whoami/errors.go
  messages/whoami/messages.go
  pkg/cmd/root/root.go
  pkg/cmd/whoami/whoami.go
Labels: enhancement

#704 fix: after the first deploy, we should not update rules engine
  go.mod
  pkg/cmd/deploy/manifest.go
Labels: bug, ship

#705 fix: remove projectRoot var to avoid build problems
  pkg/cmd/build/build.go
  pkg/cmd/build/run.go
  pkg/cmd/init/template.go
  pkg/cmd/link/template.go
  pkg/contracts/contracts.go
Labels: bug, show
