Repository aziontech/azion, pull requests merged in 2024-10, with the labels that each got.

#954 feat: add initial equalized deploy command
  .github/workflows/deploy_stage.yml
  .github/workflows/e2e_test.yml
  Makefile
  cmd/azion/main.go
  env/prod
  env/stage
  go.mod
  go.sum
  messages/deploy/errors.go
  messages/deploy/messages.go
  messages/edge_storage/messages.go
  pkg/api/storage/credentials.go
  pkg/api/storage/storage.go
  pkg/cmd/delete/edge_storage/bucket/bucket.go
  pkg/cmd/deploy/bucket.go
  pkg/cmd/deploy/bucket_test.go
  pkg/cmd/deploy/clients.go
  pkg/cmd/deploy/deploy.go
  pkg/cmd/deploy/deploy_test.go
  pkg/cmd/deploy/fixtures/response.json
  pkg/cmd/deploy/fixtures/responselogs.json
  pkg/cmd/deploy/fixtures/responses3.json
  pkg/cmd/deploy/purge.go
  pkg/cmd/deploy/requests.go
  pkg/cmd/deploy/scriptrunner.go
  pkg/cmd/deploy/upload.go
  pkg/cmd/deploy/worker.go
  pkg/cmd/deploy_remote/deploy.go
  pkg/cmd/deploy_remote/requests.go
  pkg/cmd/deploy_remote/upload.go
  pkg/cmd/deploy_remote/worker.go
  pkg/cmd/init/init.go
  pkg/contracts/contracts.go
  pkg/token/models.go
  scripts/e2e.sh
  scripts/test.sh
  utils/helpers.go
Labels: feature, do not merge

#968 test: unit tests for schedule package
  pkg/cmd/delete/edge_storage/bucket/bucket.go
  pkg/schedule/bucket_test.go
  pkg/schedule/schedule.go
  pkg/schedule/schedule_test.go
Labels: testing

#976 feat: new flag --port in dev command
  messages/dev/messages.go
  pkg/cmd/dev/dev.go
  pkg/cmd/dev/vulcan.go
Labels: feature
